theme: jekyll-theme-minimal
title: Beer to success üçª
description: by Tim Brunner, Dana Kalaaji, Cyril Golaz, Alexander Odermatt and Ajkuna Seipi
show_downloads: False
navigation: False 
google_analytics: UA-XXXXXXXXX-X
```

